using JasperFx;
using JasperFx.Descriptors;
using JasperFx.Events;
using Polecat.Tests.Reading;

namespace Polecat.Tests;

/// <summary>
/// Coverage for <c>IDocumentStoreUsageSource.TryCreateUsage</c> on Polecat's
/// <see cref="DocumentStore"/>. Mirrors the parallel tests in Marten's
/// <c>document_store_usage_tests</c>, scoped to the surface Polecat
/// actually has — no JasperFx code-gen container, no MultiHostSettings, no
/// duplicated-field enum knobs.
/// </summary>
/// <remarks>
/// Pure unit tests — no SQL Server required. Polecat's <c>TryCreateUsage</c>
/// reads in-memory configuration plus the DDL generated by Weasel's
/// <c>WriteCreateStatement</c> against a <c>DocumentTable</c>; neither path
/// opens a connection. The connection string is configured because
/// <c>StoreOptions.CreateConnectionFactory</c> validates it during
/// <c>DocumentStore</c> construction, but no command runs.
/// </remarks>
public class document_store_usage_tests
{
    private const string DummyConnectionString =
        "Server=localhost;Database=usage_tests;Integrated Security=true;TrustServerCertificate=true";

    [Fact]
    public async Task usage_carries_first_class_identity_properties()
    {
        await using var store = BuildStore(opts =>
        {
            opts.DatabaseSchemaName = "doc_usage";
            opts.AutoCreateSchemaObjects = AutoCreate.None;
            opts.Schema.For<AdvSqlDoc>();
        });

        var usage = await GetUsageAsync(store);

        usage.ShouldNotBeNull();
        usage.SubjectUri.ShouldNotBeNull();
        usage.StoreName.ShouldNotBeNullOrEmpty();
        usage.DatabaseSchemaName.ShouldBe("doc_usage");
        usage.AutoCreateSchemaObjects.ShouldBe(AutoCreate.None.ToString());
        usage.EnumStorage.ShouldNotBeNullOrEmpty();
        usage.Database.ShouldNotBeNull();
    }

    [Fact]
    public async Task usage_includes_a_descriptor_per_registered_document_mapping()
    {
        await using var store = BuildStore(opts =>
        {
            opts.DatabaseSchemaName = "doc_usage";
            opts.Schema.For<AdvSqlDoc>();
            opts.Schema.For<AdvSqlVersionedDoc>();
        });

        var usage = await GetUsageAsync(store);

        usage.Documents.Count.ShouldBeGreaterThanOrEqualTo(2);
        var aliases = usage.Documents.Select(d => d.Alias).ToList();
        aliases.ShouldContain(a => a.Contains("advsqldoc", StringComparison.OrdinalIgnoreCase));
        aliases.ShouldContain(a => a.Contains("advsqlversioneddoc", StringComparison.OrdinalIgnoreCase));

        // Document type identity threads through the descriptor — operators
        // need both the short name (for table headers) and the FullName (for
        // tooltips / drill-in).
        var docType = usage.Documents.First().DocumentType;
        docType.ShouldNotBeNull();
        docType.Name.ShouldNotBeNullOrEmpty();
        docType.FullName.ShouldNotBeNullOrEmpty();
    }

    [Fact]
    public async Task mapping_descriptor_carries_full_create_table_ddl()
    {
        await using var store = BuildStore(opts =>
        {
            opts.DatabaseSchemaName = "doc_usage";
            opts.Schema.For<AdvSqlDoc>();
        });

        var usage = await GetUsageAsync(store);
        var mapping = usage.Documents.First();

        // The DDL field is the canonical "what schema gets applied" view —
        // operators on the CritterWatch Documents tab can copy/paste this
        // straight into a SQL console. Polecat emits SQL Server DDL via
        // Weasel's DocumentTable.WriteCreateStatement.
        mapping.Ddl.ShouldNotBeNullOrEmpty();
        mapping.Ddl.ShouldContain("CREATE", Case.Insensitive);
        // SQL Server bracket-quotes identifiers — the schema name should
        // appear in the DDL.
        mapping.Ddl.ShouldContain("doc_usage", Case.Insensitive);
    }

    [Fact]
    public async Task usage_carries_flat_option_values_for_polecat_specific_settings()
    {
        await using var store = BuildStore(opts =>
        {
            opts.DatabaseSchemaName = "doc_usage";
            opts.CommandTimeout = 42;
            opts.UseNativeJsonType = false;
            opts.Schema.For<AdvSqlDoc>();
        });

        var usage = await GetUsageAsync(store);

        // CommandTimeout lifted up onto the flat Properties bag.
        usage.PropertyFor(nameof(StoreOptions.CommandTimeout))!.RawValue.ShouldBe(42);

        // Polecat-specific UseNativeJsonType lifted up flat.
        usage.PropertyFor(nameof(StoreOptions.UseNativeJsonType))!.RawValue.ShouldBe(false);

        // OpenTelemetryTrackConnections flattened from the OpenTelemetry
        // child container (mirrors the Cluster F decision on the Marten
        // side — single TrackConnections enum, no need for a child block).
        usage.PropertyFor("OpenTelemetryTrackConnections").ShouldNotBeNull();

        // HiloMaxLo lifted from HiloSequenceDefaults.
        usage.PropertyFor("HiloMaxLo").ShouldNotBeNull();
    }

    [Fact]
    public async Task code_generation_descriptor_is_null_for_polecat_today()
    {
        // Polecat doesn't expose code-generation properties on StoreOptions
        // today, so the CodeGeneration child stays null. Pin this explicitly
        // — when Polecat grows code-gen settings, we want a deliberate
        // decision (and a follow-up test) rather than silent population.
        await using var store = BuildStore(opts =>
        {
            opts.DatabaseSchemaName = "doc_usage";
            opts.Schema.For<AdvSqlDoc>();
        });

        var usage = await GetUsageAsync(store);

        usage.CodeGeneration.ShouldBeNull();
    }

    [Fact]
    public async Task max_event_sequence_is_null_when_table_unreachable()
    {
        // Dummy connection string + AutoCreate.None means MAX(seq_id) can't
        // be read — the implementation tolerates the failure and leaves
        // MaxEventSequence null so CritterWatch renders "n/a". Pins the
        // contract; without the try/catch the lookup would bubble.
        await using var store = BuildStore(opts =>
        {
            opts.DatabaseSchemaName = "doc_usage";
            opts.Schema.For<AdvSqlDoc>();
        });

        var eventUsage = await ((IEventStore)store).TryCreateUsage(CancellationToken.None);

        eventUsage.ShouldNotBeNull();
        eventUsage.MaxEventSequence.ShouldBeNull();
    }

    [Fact]
    public async Task event_store_usage_includes_tag_types()
    {
        await using var store = BuildStore(opts =>
        {
            opts.DatabaseSchemaName = "doc_usage";
            opts.EventGraph.RegisterTagType<TestTag>();
            opts.Schema.For<AdvSqlDoc>();
        });

        var eventUsage = await ((IEventStore)store).TryCreateUsage(CancellationToken.None);

        eventUsage.ShouldNotBeNull();
        eventUsage.TagTypes.ShouldContain(t => t.TagType.Contains(nameof(TestTag)));
    }

    private static DocumentStore BuildStore(Action<StoreOptions> configure)
    {
        var options = new StoreOptions
        {
            ConnectionString = DummyConnectionString,
            // Construction validates the connection string but never opens a
            // connection. AutoCreate gates DB-touching operations elsewhere,
            // not the in-memory descriptor surface we're testing.
            AutoCreateSchemaObjects = AutoCreate.None,
        };
        configure(options);
        return new DocumentStore(options);
    }

    private static async Task<DocumentStoreUsage> GetUsageAsync(DocumentStore store)
    {
        var source = (IDocumentStoreUsageSource)store;
        var usage = await source.TryCreateUsage(CancellationToken.None);
        usage.ShouldNotBeNull();
        return usage!;
    }
}

/// <summary>
/// Minimal strong-typed identifier used to register a tag type on the event
/// graph. Polecat's <c>RegisterTagType&lt;T&gt;()</c> accepts any reference
/// type that wraps a primitive; a record-struct over a Guid is the
/// canonical shape.
/// </summary>
public readonly record struct TestTag(Guid Value);
