name: Documentation PRs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  node_version: 24.x

jobs:
  run:
    name: "lint and build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Check out the code

      - name: Lint Code Base
        uses: docker://ghcr.io/igorshubovych/markdownlint-cli:latest
        with:
          args: "--config docs/.markdownlint.json docs/**/*.md"

      - uses: actions/setup-node@v6
        name: Install Node.js
        with:
          node-version: ${{ env.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Build docs
        run: npm run docs-build
